-- modgreet 0001: greeting log table
CREATE TABLE GREETLOG (
  ID        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  WHO       VARCHAR(40) NOT NULL,
  GREETED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
